
###################   Development by MR.《X》  ################

from time import sleep as timeout
import time
import sys
import os
os.system("clear")

######################  COLORS  #############################

R = '\033[1;31m'                #  red  #
G = '\033[1;32m'                #  green  #
Y = '\033[0;93m'                #  yellow  #
B = '\033[1;34m'                #  blue  #
C = '\033[1;36m'                #  cyan  #

####  The password  #######################################################################################################

def password():
	ver = input (B+'write the \033[1;31mpassword:\033[0;93m ')
	if ver == 'x' or ver == 'X' or ver == 'Mr.(X)' :
		print ('')
	else:
		print (' ')
		print (B+'Password ',R+'Error',B+' is not this')
		time.sleep(3)
		os.system('clear')
		password()
password()

####  Download logo  ######################################################################################################

def t(nn,t_):
        print(t_)
        print('')
        for i in range(0,33):
                i+=1
                txt= G+ 'ـ'*47
                f= R+ 'ـ'*i
                tt=i*3+1
                ttt=str(tt)
                print(txt+''+ttt+'%',end='\r')
                print('Legend Mr(x)  {}'.format(f),end='\r')
                time.sleep(nn)
        print('')

####  Wait message  #######################################################################################################

def wait_please():
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y .- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ..\ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ...- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ..../ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y .....- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ......\ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y .- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ../ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ...- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ....\ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y .....- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ....../ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y .- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ..\ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ...- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ..../ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y .....- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ......\ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y .- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ../ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ...- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ....\ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y .....- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ....../ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y .- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ..\ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ...- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ..../ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y .....- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ......\ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y .- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ../ ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y ...- ')
        time.sleep(0.09)
        os.system ('clear')
        print (Y+' W ',R+' A  ',B+'I  ',G+'T  ',B+', ',G+' G   ',Y+'Y   ',G+'P  ',B+'S  ',Y+'Y .... ')
        time.sleep(0.09)
        print (' ')
        t(0.1,'\n\t  \033[1;31m      [ \033[1;34m SEARCHING FOR GYPSY ....\033[1;31m  ]')
        print ('\033[1;33mDone.....................')
        print (' ')
        t(0.1,'\n\t  \033[1;31m      [ \033[1;34m TALKING TO THE GYPSY ....\033[1;31m ]')
        print ('\033[1;33mDone.....................')
        print (' ')
        t(0.1,'\n\t  \033[1;31m    [ \033[1;34m LOADING , FUKING THE GYPSY ....\033[1;31m ]')
        print ('\033[1;33mDone.....................')
        print (' ')
        t(0.1,'\n\t  \033[1;31m        [ \033[1;34m RECHECK ACTIONS ....\033[1;31m ]')
        time.sleep(0.2)
        print ('\033[1;33mDone.....................')
        print (' ')
wait_please()

####   Hi message  ###########################################################################################################


def hi_legend():
	time.sleep(0.09)
	os.system('clear')
	print (' ')
	print (' ')
	print (B+'       W')
	time.sleep(0.09)
	os.system('clear')
	print ("")
	print (B+'       W E')
	time.sleep(0.09)
	os.system('clear')
	print ("")
	print (B+'       W E L')
	time.sleep(0.09)
	os.system('clear')
	print ("")
	print (B+'       W E L C')
	time.sleep(0.09)
	os.system('clear')
	print ("")
	print (B+'       W E L C O')
	time.sleep(0.09)
	os.system('clear')
	print ("")
	print (B+'       W E L C O M')
	time.sleep(0.09)
	os.system('clear')
	print ("")
	print (B+'       W E L C O M E')
	time.sleep(0.09)
	os.system('clear')
	print ("")
	print (B+'       W E L C O M E',R+'  B')
	time.sleep(0.09)
	os.system('clear')
	print ("")
	print (B+'       W E L C O M E',R+'  B A')
	time.sleep(0.09)
	os.system('clear')
	print ("")
	print (B+'       W E L C O M E',R+'  B A C')
	time.sleep(0.09)
	os.system('clear')
	print ("")
	print (B+'       W E L C O M E',R+'  B A C K :')



####   The logo  ##############################################################################################################

def logo():
        time.sleep(0.09)
        print ( '         _       _____   _____   _____   __   _   _____  ')
        time.sleep(0.09)
        print ('        | |     | ____| /  ___| | ____| |  \ | | |  _  \ ')
        time.sleep(0.09)
        print ('        | |     | |__   | |     | |__   |   \| | | | | | ')
        time.sleep(0.09)
        print ('        | |     |  __|  | |  _  |  __|  | |\   | | | | | ')
        time.sleep(0.09)
        print ('        | |___  | |___  | |_| | | |___  | | \  | | |_| | ')
        time.sleep(0.09)
        print ('        |_____| |_____| \_____/ |_____| |_|  \_| |_____/ ')
        print ('')



####  The log in message  ##############################################################################################################

def message():
	time.sleep(0.09)
	print ('	the',B+' login ',R+'has been compieted ',B+'successfully. ')
	time.sleep(0.09)
	print ('')
	print (B+'        Lets ',R+'play ',B+'(0_0)                        ',B+'TERMUX ',R+'TOOLS ',B+'(0_0)')


##############################################################################################################



####   Termux tools  ##########################################################################################

def termux_tools():
	hi_legend()
	logo()
	message()
	time.sleep(0.09)
	print (        Y+"     _________________________________________________________________")
	print (        R+"     ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗                         ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗")
	print (        R+"     ╢                   ╢                         ╢                   ╢")
	print (        R+"     ╢  ",B+"  1-",Y+"Lazymux   ",R+"╢",B+"==《 LEGEND MR.(X) 》==",R+"╢",B+" 2-",Y+"WiFiTe2 TOOL ",R+"╢")
	print (        R+"     ╢                   ╢                         ╢                   ╢")
	print (        R+"     ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝                         ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝")
	print (        Y+"     _________________________________________________________________")
	time.sleep(0.09)
	print (        Y+"     _________________________________________________________________")
	print (        R+"     ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗                         ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗")
	print (        R+"     ╢                   ╢                         ╢                   ╢")
	print (        R+"     ╢",B+"3-",Y+"HT-WPS-Breaker",R+"╢",B+"==《 LEGEND MR.(X) 》==",R+"╢",B+"4-",Y+"GloomFramework",R+"╢")
	print (        R+"     ╢                   ╢                         ╢                   ╢")
	print (        R+"     ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝                         ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝")
	print (        Y+"     _________________________________________________________________")
	time.sleep(0.09)
	print (        Y+"     _________________________________________________________________")
	print (        R+"     ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗                         ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗")
	print (        R+"     ╢                   ╢                         ╢                   ╢")
	print (        R+"     ╢  ",B+"   5-",Y+"Hunner   ",R+"╢",B+"==《 LEGEND MR.(X) 》==",R+"╢",B+"   6-",Y+"fluxion    ",R+"╢")
	print (        R+"     ╢                   ╢                         ╢                   ╢")
	print (        R+"     ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝                         ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝")
	print (        Y+"     _________________________________________________________________")
	time.sleep(0.09)
	print (        Y+"     _________________________________________________________________")
	print (        R+"     ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗                         ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗")
	print (        R+"     ╢                   ╢                         ╢                   ╢")
	print (        R+"     ╢  ",B+"  7-",Y+"ngrok     ",R+"╢",B+"==《 LEGEND MR.(X) 》==",R+"╢",B+"     8-",Y+"MITMf ",R+"   ╢")
	print (        R+"     ╢                   ╢                         ╢                   ╢")
	print (        R+"     ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝                         ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝")
	print (        Y+"     _________________________________________________________________")
	time.sleep(0.09)
	print (        R+"	                  ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗")
	print (        R+"	                  ╢                         ╢")
	print (        R+"	                  ╢",Y+" Enter ",B+"99",Y+" to get out",R+" ╢")
	print (	       R+"	                  ╢                         ╢")
	print (        R+"	                  ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝")
	print ('')
	time.sleep(0.09)
	ver2 = input ('\033[1;33mLEGEND > Teemux Tools\033[1;31m (0_0)\033[1;33m »»» ')

	if ver2 == '99':
		time.sleep(2)
		os.system('clear')
		Selection()



	elif ver2 == '1':
		os.system ('clear')
		time.sleep(0.09)
		print (" ")
		print (          R+"     _           ___   ______ __    __      ___  ___   _   _  __    __   ")
		print (          G+"    | |         /   | |___  / \ \  / /     /   |/   | | | | | \ \  / /   ")
		print (          Y+"    | |        / /| |    / /   \ \/ /     / /|   /| | | | | |  \ \/ /    ")
		print (          B+"    | |       / / | |   / /     \  /     / / |__/ | | | | | |   }  {     ")
		print (          C+"    | |___   / /  | |  / /__    / /     / /       | | | |_| |  / /\ \    ")
		print (          R+"    |_____| /_/   |_| /_____|  /_/     /_/        |_| \_____/ /_/  \_\   ")
		time.sleep(0.09)
		print (" ")
		print (          B+'    Lazymux is a tool installer that is ')
		print (          B+'    speciallyLazymux is a tool installer that is')
		print (          B+'    specially made for termux user which')
		print (          B+'    provides a lot of tool mainly used tools in')
		print (          B+'    termux and its easy to use, Lazymux install')
		print (          B+'    any of the given tools provided by it from')
		print (          B+'    itself with just one click, and its often get updated.')
		time.sleep(0.09)
		print (" ")
		print (        Y+"     _________________________________________________________________")
		print (        R+"     ╔╧╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗                         ╔╧╤╧╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗")
		print (        R+"     ╢                    ╢                         ╢                    ╢")
		print (        R+"     ╢ ",B+"1-",Y+"Open Lazymux  ",R+"╢",B+"==《 LEGEND MR.(X) 》==",R+"╢",B+"2-",Y+"Install Lazymux",R+"╢")
		print (        R+"     ╢                    ╢                         ╢                    ╢")
		print (        R+"     ╚╤╧╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝                         ╚╤╧╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝")
		print (        Y+"     _________________________________________________________________")
		print (        R+"                        ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗")
		print (        R+"                        ╢                         ╢")
		print (        R+"                        ╢",Y+" Enter ",B+"99",Y+" to get out",R+" ╢")
		print (        R+"                        ╢                         ╢")
		print (        R+"                        ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝")
		print ("")
		print ("")

		time.sleep(0.09)
		install_open = input ('\033[1;33mLEGEND > Termux Tools > Lazymux\033[1;31m (0_0)\033[1;33m »»» ')

		if install_open == '2':
			print ("Loading..........!")
			print (' ')
			t(0.1,'\n\t            \033[1;31m [   Install Lazymux .... ]')
			timeout(0.09)
			print ("done.....")
			time.sleep(1)
			os.system ('clear')
			os.system ('apt update && apt upgrade -y')
			os.system ('clear')
			os.system ('pkg update')
			os.system ('clear')
			os.system ('git clone https://github.com/Gameye98/Lazymux')
			os.system ('mv Lazymux ~')
			os.system ('clear')
			termux_tools()

		elif install_open == '1':
			print ("Loading..........!")
			print (' ')
			t(0.1,'\n\t     \033[1;31m    [   Loading Open Lazymux .... ]')
			timeout(0.09)
			print ("done.....")
			os.chdir ('Lazymux')
			os.system ('python lazymux.py')
			termux_tools()

		else:
			termux_tools()



	elif ver2 == '2':
		os.system ('clear')
		time.sleep(0.09)
		print (" ")
		print (        R+"       _          __  _   _____   _   _____   _____   _____  ")
		print (        G+"      | |        / / | | |  ___| | | |_   _| | ____| /___  \ ")
		print (        Y+"      | |  __   / /  | | | |__   | |   | |   | |__    ___| | ")
		print (        B+"      | | /  | / /   | | |  __|  | |   | |   |  __|  /  ___/ ")
		print (        C+"      | |/   |/ /    | | | |     | |   | |   | |___  | |___  ")
		print (        R+"      |___/|___/     |_| |_|     |_|   |_|   |_____| |_____| ")
		time.sleep(0.09)
		print (" ")
		print (        B+'      Wifite runs existing wireless-auditing tools')
		print (        B+'      for you. Stop memorizing command')
		print (        B+'      arguments & switches!')
		print (        B+'      Wifite is designed to use all known')
		print (        B+'      methods for retrieving the password of a')
		print (        B+'      wireless access point (router). These methods include:')
		print (        B+'      • WPS: The Offline Pixie-Dust attack')
		print (        B+'      • WPS: The Online Brute-Force PIN attack')
		print (        B+'      • WPA: The WPA Handshake Capture + offline crack.')
		print (        B+'      • WPA: The PMKID Hash Capture + offline crack.')
		print (        B+'      • WEP: Various known attacks against WEP, including')
		print (        B+'         fragmentation, chop-chop, aireplay, etc.')
		print (        B+'      Run wifite, select your targets, and Wifite')
		print (        B+'      will automatically start trying to capture or crack the password.')
		time.sleep(0.09)
		print (" ")
		print (        Y+'      [',R+'+',Y+']Note: this tool needs a root')
		time.sleep(0.09)
		print (" ")
		print (        Y+"     _________________________________________________________________")
		print (        R+"     ╔╧╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗                         ╔╧╤╧╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗")
		print (        R+"     ╢                    ╢                         ╢                    ╢")
		print (        R+"     ╢ ",B+"1-",Y+"Open wifite2  ",R+"╢",B+"==《 LEGEND MR.(X) 》==",R+"╢",B+"2-",Y+"Install wifite2",R+"╢")
		print (        R+"     ╢                    ╢                         ╢                    ╢")
		print (        R+"     ╚╤╧╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝                         ╚╤╧╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝")
		print (        Y+"     _________________________________________________________________")
		print (        R+"                        ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗")
		print (        R+"                        ╢                         ╢")
		print (        R+"                        ╢",Y+" Enter ",B+"99",Y+" to get out",R+" ╢")
		print (        R+"                        ╢                         ╢")
		print (        R+"                        ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝")
		print ("")
		print ("")

		time.sleep(0.09)
		install_open = input ('\033[1;33mLEGEND > Termux Tools > Wifite2\033[1;31m (0_0)\033[1;33m »»» ')

		if install_open == '2':
			print ("Loading..........!")
			timeout(2)
			t(0.1,'\n\t            \033[1;31m [   Install wifite2 .... ]')
			print ("done.....")
			time.sleep(2)
			os.system ('clear')
			os.system ('git clone https://github.com/derv82/wifite2')
			os.system ('mv wifite2 ~')
			os.system('clear')
			termux_tools()

		elif install_open == '1':
			print ("Loading..........!")
			print (' ')
			t(0.1,'\n\t     \033[1;31m    [   Loading Open Lazymux .... ]')
			timeout(0.09)
			print ("done.....")
			os.chdir ('wifite2')
			os.system ('python Wifite.py')
			termux_tools()
		else:
			termux_tools()



	elif ver2 == '3':
		os.system ('clear')

		print ("Loading..........!")
		timeout(2)
		t(0.1,'\n\t   \033[1;31m[   PLEASE WAIT .... ]')
		print ("done.....")
		time.sleep(2)
		os.system ('clear')
		os.system ('git clone https://github.com/SilentGhostX/HT-WPS-Breaker.git')
		os.system ('mv HT-WPS-Breaker.git ~ ')
		os.system('clear')
		print ('Done....You will find it at home ')
		termux_tools()

	elif ver2 == '4':
		os.system ('clear')
		print ("Loading..........!")
		timeout(2)
		t(0.1,'\n\t   \033[1;31m[   PLEASE WAIT .... ]')
		print ("done.....")
		time.sleep(2)
		os.system ('clear')
		os.system ('git clone https://github.com/StreetSec/Gloom-Framework')
		os.system ('mv Gloom-Framework ~')
		os.system('clear')
		print ('Done....You will find it at home ')
		time.sleep(3)
		termux_tools()

	elif ver2 == '5':
		os.system ('clear')
		print ("Loading..........!")
		timeout(2)
		t(0.1,'\n\t   \033[1;31m[   PLEASE WAIT .... ]')
		print ("done.....")
		time.sleep(2)
		os.system ('clear')
		os.system ('git clone https://github.com/b3-v3r/Hunner')
		os.system ('mv Hunner ~')
		os.system('clear')
		print ('Done....You will find it at home ')
		time.sleep(3)
		termux_tools()

	elif ver2 == '6':
		os.system ('clear')
		print ("Loading..........!")
		timeout(2)
		t(0.1,'\n\t   \033[1;31m[   PLEASE WAIT .... ]')
		print ("done.....")
		time.sleep(2)
		os.system ('clear')
		os.system ('git clone https://github.com/wi-fi-analyzer/fluxion')
		os.system ('mv fluxion ~')
		os.system('clear')
		print ('Done....You will find it at home ')
		time.sleep(3)
		termux_tools()

	elif ver2 == '7':
		os.system ('clear')
		print ("Loading..........!")
		timeout(2)
		t(0.1,'\n\t   \033[1;31m[   PLEASE WAIT .... ]')
		print ("done.....")
		time.sleep(2)
		os.system ('clear')
		os.system ('git clone https://github.com/inconshreveable/ngrok.git')
		os.system ('mv ngrok.git ~')
		os.system('clear')
		print ('Done....You will find it at home ')
		time.sleep(3)
		termux_tools()

	elif ver2 == '8':
		os.system ('clear')
		print ("Loading..........!")
		timeout(2)
		t(0.1,'\n\t   \033[1;31m[   PLEASE WAIT .... ]')
		print ("done.....")
		time.sleep(2)
		os.system ('clear')
		os.system ('git clone https://github.com/byt3bl33d3r/MITMf')
		os.system ('mv MITMf ~')
		os.system('clear')
		print ('Done....You will find it at home ')
		time.sleep(3)
		termux_tools()

	else:
		termux_tools()


###################################################################################################################




#############################################  this is the end   #######################################################################

def Selection():
	os.system('clear')
	hi_legend()
	logo()
	message()
	time.sleep(0.09)

	print (        Y+"     _________________________________________________________________") 
	print (        R+"     ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗                         ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗")
	print (        R+"     ╢                   ╢                         ╢                   ╢")
	print (        R+"     ╢",B+" 1-",Y+"termux tools ",R+"╢",B+"==《 LEGEND MR.(X) 》==",R+"╢",B+"  2-",Y+"MetaSploit  ",R+"╢")
	print (        R+"     ╢                   ╢                         ╢                   ╢")
	print (        R+"     ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝                         ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝")
	print (        Y+"     _________________________________________________________________")
	time.sleep(0.09)
	print (        R+"                        ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╗")
	print (        R+"                        ╢                         ╢")
	print (        R+"                        ╢",Y+" Enter ",B+"99",Y+" to get out",R+" ╢")
	print (        R+"                        ╢                         ╢")
	print (        R+"                        ╚╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╝")
	print ("")
	print ("")
	ver3 = input ('\033[1;33mLEGEND\033[1;31m (0_0)\033[1;33m »»» ')
	if ver3 == "1":
		os.system ('clear')
		print ("Loading..........!")
		timeout(2)
		t(0.1,'\n\t   \033[1;31m          [   PLEASE WAIT .... ]')
		print ("done.....")
		time.sleep(2)
		os.system ('clear')
		termux_tools()

	elif ver3 == "2":
		os.system ('clear')
		print ("Loading..........!")
		timeout(2)
		t(0.1,'\n\t   \033[1;31m          [   PLEASE WAIT .... ]')
		print ("done.....")
		time.sleep(2)
		os.system ('clear')



	elif ver3 == "99":
		os.system ('clear')
		print ("Loading..........!")
		timeout(2)
		t(0.1,'\n\t   \033[1;31m          [   PLEASE WAIT .... ]')
		print ("done.....")
		time.sleep(2)
		os.system ('clear')

	else:
		time.sleep(1)
		print ("")
		print ('     Error, please choos a number ')
		time.sleep(4)
		Selection()
Selection()
